### PR TITLE
feat: add legal disclaimer in footer

### LINKED ISSUE #2: add short legal disclaimer

### PR DESCRIPTION
**Pull request by hagoptaminian**
closes #2

### CODE REVIEW

**Comment by hagoptaminian** [comment]
looks like this:

Screen Shot 2021-02-05 at 11 28 54 AM

**Comment by juancarlosfarah** [comment]
@hagoptaminian, what do you think? I think it's a bit intense. What if we add a link "Legal" under "Contact Us" and put that in a new page?

**Comment by juancarlosfarah** [comment]
@hagoptaminian, I still think that we should put this in a separate page, if possible.

**Comment by hagoptaminian** [comment]
updated PR here: https://github.com/graasp/graasp-content-insights/pull/4

**Pull request closed without merging**
